//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Finalnyjj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График отпуска.
    /// </summary>
    // *** Start programmer edit section *** (ГрафикОтпуска CustomAttributes)

    // *** End programmer edit section *** (ГрафикОтпуска CustomAttributes)
    [AutoAltered()]
    [Caption("График отпуска")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикОтпускаE", new string[] {
            "Номер as \'Номер\'",
            "ДатаДок as \'Дата документа\'",
            "ДатаНач as \'Дата начала\'",
            "КолДней as \'Количество дней\'",
            "Отправлено as \'Отправлено\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'",
            "Сотрудники.Имя as \'Имя\'",
            "Сотрудники.Отчество as \'Отчество\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия"})]
    [MasterViewDefineAttribute("ГрафикОтпускаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ГрафикОтпускаL", new string[] {
            "Номер as \'Номер\'",
            "ДатаДок as \'Дата документа\'",
            "ДатаНач as \'Дата начала отпуска\'",
            "КолДней as \'Количество дней\'",
            "Отправлено as \'Отправлено\'",
            "Сотрудники.Фамилия as \'Фамилия\'",
            "Сотрудники.Имя as \'Имя\'",
            "Сотрудники.Отчество as \'Отчество\'"})]
    public class ГрафикОтпуска : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fДатаДок = System.DateTime.Now;
        
        private System.DateTime fДатаНач;
        
        private string fКолДней;
        
        private bool fОтправлено = false;
        
        private IIS.Finalnyjj.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ГрафикОтпуска CustomMembers)

        // *** End programmer edit section *** (ГрафикОтпуска CustomMembers)

        
        /// <summary>
        /// ДатаДок.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуска.ДатаДок CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуска.ДатаДок CustomAttributes)
        public virtual System.DateTime ДатаДок
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаДок Get start)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаДок Get start)
                System.DateTime result = this.fДатаДок;
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаДок Get end)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаДок Set start)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаДок Set start)
                this.fДатаДок = value;
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаДок Set end)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаДок Set end)
            }
        }
        
        /// <summary>
        /// ДатаНач.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуска.ДатаНач CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуска.ДатаНач CustomAttributes)
        public virtual System.DateTime ДатаНач
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаНач Get start)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаНач Get start)
                System.DateTime result = this.fДатаНач;
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаНач Get end)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаНач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаНач Set start)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаНач Set start)
                this.fДатаНач = value;
                // *** Start programmer edit section *** (ГрафикОтпуска.ДатаНач Set end)

                // *** End programmer edit section *** (ГрафикОтпуска.ДатаНач Set end)
            }
        }
        
        /// <summary>
        /// КолДней.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуска.КолДней CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуска.КолДней CustomAttributes)
        [StrLen(255)]
        public virtual string КолДней
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.КолДней Get start)

                // *** End programmer edit section *** (ГрафикОтпуска.КолДней Get start)
                string result = this.fКолДней;
                // *** Start programmer edit section *** (ГрафикОтпуска.КолДней Get end)

                // *** End programmer edit section *** (ГрафикОтпуска.КолДней Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.КолДней Set start)

                // *** End programmer edit section *** (ГрафикОтпуска.КолДней Set start)
                this.fКолДней = value;
                // *** Start programmer edit section *** (ГрафикОтпуска.КолДней Set end)

                // *** End programmer edit section *** (ГрафикОтпуска.КолДней Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуска.Номер CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуска.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.Номер Get start)

                // *** End programmer edit section *** (ГрафикОтпуска.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ГрафикОтпуска.Номер Get end)

                // *** End programmer edit section *** (ГрафикОтпуска.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.Номер Set start)

                // *** End programmer edit section *** (ГрафикОтпуска.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ГрафикОтпуска.Номер Set end)

                // *** End programmer edit section *** (ГрафикОтпуска.Номер Set end)
            }
        }
        
        /// <summary>
        /// Отправлено.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуска.Отправлено CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуска.Отправлено CustomAttributes)
        public virtual bool Отправлено
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.Отправлено Get start)

                // *** End programmer edit section *** (ГрафикОтпуска.Отправлено Get start)
                bool result = this.fОтправлено;
                // *** Start programmer edit section *** (ГрафикОтпуска.Отправлено Get end)

                // *** End programmer edit section *** (ГрафикОтпуска.Отправлено Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.Отправлено Set start)

                // *** End programmer edit section *** (ГрафикОтпуска.Отправлено Set start)
                this.fОтправлено = value;
                // *** Start programmer edit section *** (ГрафикОтпуска.Отправлено Set end)

                // *** End programmer edit section *** (ГрафикОтпуска.Отправлено Set end)
            }
        }
        
        /// <summary>
        /// График отпуска.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуска.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуска.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Finalnyjj.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.Сотрудники Get start)

                // *** End programmer edit section *** (ГрафикОтпуска.Сотрудники Get start)
                IIS.Finalnyjj.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ГрафикОтпуска.Сотрудники Get end)

                // *** End programmer edit section *** (ГрафикОтпуска.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуска.Сотрудники Set start)

                // *** End programmer edit section *** (ГрафикОтпуска.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ГрафикОтпуска.Сотрудники Set end)

                // *** End programmer edit section *** (ГрафикОтпуска.Сотрудники Set end)
            }
        }
        
        // *** Start programmer edit section *** (ГрафикОтпуска.Отправить CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуска.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (ГрафикОтпуска.Отправить method implementation)
            return;
            // *** End programmer edit section *** (ГрафикОтпуска.Отправить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикОтпускаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикОтпускаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикОтпускаE", typeof(IIS.Finalnyjj.ГрафикОтпуска));
                }
            }
            
            /// <summary>
            /// "ГрафикОтпускаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикОтпускаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикОтпускаL", typeof(IIS.Finalnyjj.ГрафикОтпуска));
                }
            }
        }
    }
}
